apiVersion: v1
kind: Pod
metadata:
  name: nginx-lb 
  labels:
    app: nginx-lb
    demo: service 
spec:
  containers:
    - name: nginx-lb
      image: nginx # it is a public image, so k8 pulling it from docker hub
      ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service-lb
spec:
  type: LoadBalancer
  selector:
    app: nginx-lb
    demo: service 
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80 # container port