apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static
spec:
  accessModes:
  - ReadWriteOnce #EBS volumne should have readwriteonce, because it is HD
  capacity:
    storage: 10Gi # created EBS with 10 Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0dc8f582b7ff62651

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set. This is empty for static provisioning
  volumeName: ebs-static # Name of the persistent volume from which you are requesting the volume to the pod
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
# now attach the PVC to the pod
apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    demo: ebs-static
spec:
  containers:
  - name: nginx
    image: nginx       
    volumeMounts:
    - name: nginx-data
      mountPath: /usr/share/nginx/html
  nodeSelector:
    zone: 1d
 
  volumes:
  - name: nginx-data
    persistentVolumeClaim:
      claimName: ebs-static # name of the persistent volume claim


---

apiVersion: v1
kind: Service
metadata:
  name: ebs-static
spec:
  type: LoadBalancer
  selector:    
    demo: ebs-static 
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80 # container port