apiVersion: v1
kind: Pod
metadata:
  name: multi-container  
spec:
# list of containers
  containers:
    - name: nginx
      image: nginx # it is a public image, so k8 pulling it from docker hub
      ports:
        - containerPort: 80
    - name: almalinux
      image: almalinux:8
      command: ["sleep", "300"]
      
