apiVersion: v1
kind: Pod
metadata:
  name: annotations
  labels:
    course: Devops
    trainer: ShivaKumar  # if space, should be in double cotes
  annotations:
    com.roboshop.training.duration: "120 hours"
    jenkins.url: "https://jenkins.com/roboshop/catalogue#45"
spec:
# list of containers
  containers:
    - name: hello-pod
      image: nginx # it is a public image, so k8 pulling it from docker hub
      ports:
        - containerPort: 80