apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  namespace: roboshop
spec:
# list of containers
  containers:
    - name: hello-pod
      image: nginx # it is a public image, so k8 pulling it from docker hub
      ports:
        - containerPort: 80
      resources:
        requests:          
          cpu: "100m"
          memory: "64Mi"
        limits:
          cpu: "200m"
          memory: "128Mi"
          
