apiVersion: v1
kind: Pod
metadata:
  name: node-anti-affinity-1
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: project
            operator: NotIn
            values:
            - roboshop
            
  containers:
  - name: node-anti-affinity-1
    image: nginx
  
---

apiVersion: v1
kind: Pod
metadata:
  name: node-anti-affinity-2
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: project
            operator: NotIn
            values:
            - roboshop
            
  containers:
  - name: node-anti-affinity-2
    image: nginx

---
apiVersion: v1
kind: Pod
metadata:
  name: node-anti-affinity-3
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: project
            operator: NotIn
            values:
            - roboshop
            
  containers:
  - name: node-anti-affinity-3
    image: nginx

---
apiVersion: v1
kind: Pod
metadata:
  name: node-anti-affinity-4
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: project
            operator: NotIn
            values:
            - roboshop
            
  containers:
  - name: node-anti-affinity-4
    image: nginx