apiVersion: v1
kind: Pod
metadata:
  name: affinity-pod-1
spec:
# list of containers
  containers:
    - name: hello-pod
      image: nginx # it is a public image, so k8 pulling it from docker hub
      ports:
        - containerPort: 80