apiVersion: v1
kind: Pod
metadata:
  name: affinity-pod-1
spec:
# list of containers
  containers:
    - name: hello-pod
      image: nginx # it is a public image, so k8 pulling it from docker hub
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: affinity-pod-2
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: name
            operator: In
            values:
            - affinity-pod-1        
  containers:
  - name: with-pod-affinity
    image: nginx
